// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCon5tMAPUHwaA0EBLVnoUAqE-TQ5XW1b4',
    appId: '1:223072121044:web:aa3b9f8cfbbfb4260f8b41',
    messagingSenderId: '223072121044',
    projectId: 'snackr-b0d91',
    authDomain: 'snackr-b0d91.firebaseapp.com',
    storageBucket: 'snackr-b0d91.firebasestorage.app',
    measurementId: 'G-4Y5SPDDEMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU5e3K9Utni3nzOS7Q3ggv3PPtsFy7_LQ',
    appId: '1:223072121044:android:7931b2c881497a500f8b41',
    messagingSenderId: '223072121044',
    projectId: 'snackr-b0d91',
    storageBucket: 'snackr-b0d91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwBPTHmpJT8hI9YAJ2BE1Uq76RC12saXA',
    appId: '1:223072121044:ios:9d5c8a9bb67be45b0f8b41',
    messagingSenderId: '223072121044',
    projectId: 'snackr-b0d91',
    storageBucket: 'snackr-b0d91.firebasestorage.app',
    iosBundleId: 'com.example.snackr',
  );
}
